# Generated by Django 3.2.10 on 2021-12-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_meetup'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='meetup',
            managers=[
            ],
        ),
    ]
