# Generated by Django 3.2.10 on 2021-12-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_meetup_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetup',
            options={},
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='meetups',
            field=models.ManyToManyField(to='tgbot.MeetUp'),
        ),
    ]
